name: Deploy to EKS

on:
  push:
    branches:
      - main  # Runs workflow on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Change to your AWS region

    - name: Install Kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Install eksctl
      run: |
        curl -sSLO "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz"
        tar -xzf eksctl_Linux_amd64.tar.gz
        sudo mv eksctl /usr/local/bin/

    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Build and Push Docker Image
      env:
        IMAGE_TAG: latest
        DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/hospital-app
      run: |
        docker build -t $DOCKER_REPO:$IMAGE_TAG .
        docker push $DOCKER_REPO:$IMAGE_TAG

    - name: Deploy to EKS
      run: |
        aws eks --region us-east-1 update-kubeconfig --name my-cluster
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/service.yaml
